"""add classification fields to mentions

Revision ID: 19e01c8137d1
Revises: e42bef82bbf9
Create Date: 2026-09-04 22:23:54.968755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e01c8137d1'
down_revision: Union[str, None] = 'e42bef82bbf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentions', sa.Column('sentiment_confidence', sa.Float(), nullable=True))
    op.add_column('mentions', sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mentions', sa.Column('alert_category', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentions', 'alert_category')
    op.drop_column('mentions', 'classified_at')
    op.drop_column('mentions', 'sentiment_confidence')
    # ### end Alembic commands ###
