"""add event log, mention assignment/resolution, response time baseline

Revision ID: 4f7259f81e17
Revises: e60b5becc305
Create Date: 2026-09-04 11:05:13.752796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7259f81e17'
down_revision: Union[str, None] = 'e60b5becc305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mention_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_event_type_occurred_at', 'events', ['event_type', 'occurred_at'], unique=False)
    op.create_table('response_time_baselines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_description', sa.String(length=512), nullable=False),
    sa.Column('response_time_hours', sa.Float(), nullable=True),
    sa.Column('captured_by', sa.String(length=255), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('mentions', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mentions', sa.Column('assigned_to', sa.String(length=255), nullable=True))
    op.add_column('mentions', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_mentions_sentiment_assigned_at', 'mentions', ['sentiment', 'assigned_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mentions_sentiment_assigned_at', table_name='mentions')
    op.drop_column('mentions', 'resolved_at')
    op.drop_column('mentions', 'assigned_to')
    op.drop_column('mentions', 'assigned_at')
    op.drop_table('response_time_baselines')
    op.drop_index('ix_events_event_type_occurred_at', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
