"""initial schema: mentions, ingestion_runs

Revision ID: e60b5becc305
Revises: 
Create Date: 2026-09-04 10:42:02.924660

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e60b5becc305'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('items_seen', sa.Integer(), nullable=False),
    sa.Column('items_ingested', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_runs_source_started_at', 'ingestion_runs', ['source', 'started_at'], unique=False)
    op.create_table('mentions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('sentiment', sa.String(length=16), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('has_reply', sa.Boolean(), nullable=True),
    sa.Column('headline', sa.String(length=512), nullable=True),
    sa.Column('tier', sa.String(length=32), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_mentions_source_external_id')
    )
    op.create_index('ix_mentions_kind', 'mentions', ['kind'], unique=False)
    op.create_index('ix_mentions_source_published_at', 'mentions', ['source', 'published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mentions_source_published_at', table_name='mentions')
    op.drop_index('ix_mentions_kind', table_name='mentions')
    op.drop_table('mentions')
    op.drop_index('ix_ingestion_runs_source_started_at', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
